name: metcalcs-dev               # the name is ignored when CI runs `conda env update -n base`
channels:
  - conda-forge                  # single channel keeps things deterministic
dependencies:
  # ---- runtime ----
  - python >=3.9,<3.13           # same range supported in pyproject
  - numpy
  - pandas

  # ---- documentation ----
  - sphinx
  - sphinx_rtd_theme

  # ---- testing / QA ----
  - pytest
  - coverage
  - mypy
  - ruff
  - black

  # ---- packaging / release helpers ----
  - bump2version
  - twine
  - wheel
  - tox
  - watchdog                    # file-watching helper used in dev workflow

  # ---- pip section ----
  - pip
  - pip:
      - -e .                    # install metcalcs from the local checkout in editable mode
